version: '2.1'
services:
  beego:
    build:
      context: .
    image: ddc_beego
    # cap and privileged needed for slowlog
    cap_add:
      - SYS_PTRACE
    privileged: true
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
    extra_hosts:
      - "service01:172.16.0.95"
      - "service02:172.16.0.95"
      # - "service02:172.16.0.74"
      - "servicestaging01:172.16.0.95"
      - "servicestaging02:172.16.0.95"
      # - "servicestaging02:172.16.0.74"
    environment:
      TZ: "Asia/Jakarta"
    mem_limit: 1024m
    volumes:
      - ./:/docker/
      - gosrc:/go/src/
      - gosrc:/var/go/src/
      - gopkg:/go/pkg/
      - gopkg:/var/go/pkg/
    entrypoint: "bee run"
    restart: always
