version: '2.1'
services:
  beego:
    build:
      context: .
    image: ddc_beego
    # cap and privileged needed for slowlog
    cap_add:
      - SYS_PTRACE
    privileged: true
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
    extra_hosts:
      - "service01:172.18.0.1"
      - "service02:172.18.0.1"
      - "servicestaging01:172.18.0.1"
      - "servicestaging02:172.18.0.1"
    environment:
      TZ: "Asia/Jakarta"
    mem_limit: 200m
    volumes:
      - ./:/docker/
      - gosrc:/go/src/
      - gosrc:/var/www/go/src/
      - gopkg:/go/pkg/
      - gopkg:/var/www/go/pkg/
      - gosrc:/home/nath/go/src/
      - gopkg:/home/nath/go/pkg/
    # entrypoint: "bee run"
    entrypoint: "/docker/docker/beego/beerun.sh"
