version: '2.1'
services:
  #######################################
  # DDC Services
  #######################################

  auth:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_auth
    ports:
      - "8083:8083"
    expose:
      - "2345"
    environment:
      GO_SVC: "ddc_authentication"
    network_mode: "host"
    working_dir: "/go/src/ddc_authentication"
    entrypoint: "./ddc_authentication"

  payment:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_payment
    ports:
      - "8087:8087"
    environment:
      GO_SVC: "ddc_payment"
    network_mode: "host"
    working_dir: "/go/src/ddc_payment"
    entrypoint: "./ddc_payment"

  profile:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_profile
    ports:
      - "8086:8086"
    environment:
      GO_SVC: "ddc_profile"
    network_mode: "host"
    working_dir: "/go/src/ddc_profile"
    entrypoint: "./ddc_profile"

  order:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_order
    ports:
      - "8085:8085"
    expose:
      - "18085"
    environment:
      GO_SVC: "ddc_order"
    network_mode: "host"
    working_dir: "/go/src/ddc_order"
    entrypoint: "./ddc_order"

  product:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_product
    ports:
      - "8084:8084"
    environment:
      GO_SVC: "ddc_product"
    network_mode: "host"
    working_dir: "/go/src/ddc_product"
    entrypoint: "./ddc_product"

  queue:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_queue
    ports:
      - "8095:8095"
    environment:
      GO_SVC: "ddc_queue"
    network_mode: "host"
    working_dir: "/go/src/ddc_queue"
    entrypoint: "./ddc_queue"

  mentoring:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_mentoring
    ports:
      - "8096:8096"
    environment:
      GO_SVC: "ddc_mentoring"
    network_mode: "host"
    working_dir: "/go/src/ddc_mentoring"
    entrypoint: "./ddc_mentoring"

#######################################
# Volumes
#######################################
volumes:
  gosrc:
    driver: local
    driver_opts:
      type: bind
      device: /var/go/src
      o: bind
  gopkg:
    driver: local
    driver_opts:
      type: bind
      device: /var/go/pkg
      o: bind
