version: '2.1'
services:
  #######################################
  # DDC Services
  #######################################

  auth:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_auth
    ports:
      - "8083:8083"
      - "9083:9083"
    expose:
      - "2345"
    environment:
      GO_SVC: "ddc_authentication"
    network_mode: "host"
    working_dir: "/go/src/ddc_authentication"
    entrypoint: "./ddc_authentication"

  payment:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_payment
    ports:
      - "8087:8087"
      - "9087:9087"
    environment:
      GO_SVC: "ddc_payment"
    network_mode: "host"
    working_dir: "/go/src/ddc_payment"
    entrypoint: "./ddc_payment"

  profile:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_profile
    ports:
      - "8086:8086"
      - "9086:9086"
    environment:
      GO_SVC: "ddc_profile"
    mem_limit: 2g
    network_mode: "host"
    working_dir: "/go/src/ddc_profile"
    entrypoint: "./ddc_profile"

  voucher:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_voucher
    ports:
      - "8089:8089"
      - "9089:9089"
    environment:
      GO_SVC: "ddc_voucher"
    network_mode: "host"
    working_dir: "/go/src/ddc_voucher"
    entrypoint: "./ddc_voucher"

  order:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_order
    ports:
      - "8085:8085"
      - "9085:9085"
    expose:
      - "18085"
    environment:
      GO_SVC: "ddc_order"
    network_mode: "host"
    mem_limit: 2048m
    working_dir: "/go/src/ddc_order"
    entrypoint: "./ddc_order"

  product:
    extends:
      file: common-services.yml
      service: beego-media
    container_name: ddc_product
    ports:
      - "8084:8084"
      - "9084:9084"
    environment:
      GO_SVC: "ddc_product"
    network_mode: "host"
    mem_limit: 2048m
    working_dir: "/go/src/ddc_product"
    entrypoint: "./ddc_product"

  queue:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_queue
    ports:
      - "8095:8095"
      - "9095:9095"
    environment:
      GO_SVC: "ddc_queue"
    network_mode: "host"
    mem_limit: 2048m
    working_dir: "/go/src/ddc_queue"
    entrypoint: "./ddc_queue"

  mentoring:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_mentoring
    ports:
      - "8096:8096"
      - "9096:9096"
    environment:
      GO_SVC: "ddc_mentoring"
    network_mode: "host"
    working_dir: "/go/src/ddc_mentoring"
    entrypoint: "./ddc_mentoring"

  shipping:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_shipping
    ports:
      - "8081:8081"
      - "9081:9081"
    environment:
      GO_SVC: "ddc_shipping"
    network_mode: "host"
    working_dir: "/go/src/ddc_shipping"
    entrypoint: "./ddc_shipping"

  scheduler:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_scheduler
    ports:
      - "8088:8088"
      - "9088:9088"
    environment:
      GO_SVC: "ddc_scheduler"
    network_mode: "host"
    working_dir: "/go/src/ddc_scheduler"
    entrypoint: "./ddc_scheduler"

  discount:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_discount
    ports:
      - "8094:8094"
      - "9094:9094"
    environment:
      GO_SVC: "ddc_discount"
    network_mode: "host"
    working_dir: "/go/src/ddc_discount"
    entrypoint: "./ddc_discount"

  notification:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_notification
    ports:
      - "8082:8082"
      - "9082:9082"
    environment:
      GO_SVC: "ddc_notification"
    network_mode: "host"
    working_dir: "/go/src/ddc_notification"
    entrypoint: "./ddc_notification"

  arisan:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_arisan
    ports:
      - "8097:8097"
      - "9087:9087"
    environment:
      GO_SVC: "ddc_arisan"
    network_mode: "host"
    working_dir: "/go/src/ddc_arisan"
    entrypoint: "./ddc_arisan"

  media:
    extends:
      file: common-services.yml
      service: beego-media
    container_name: ddc_media
    ports:
      - "8098:8098"
      - "18098:18098"
    environment:
      GO_SVC: "ddc_media"
    network_mode: "host"
    working_dir: "/go/src/ddc_media"
    entrypoint: "./ddc_media"

#######################################
# Volumes
#######################################
volumes:
  gosrc:
    driver: local
    driver_opts:
      type: bind
      device: /var/go/src
      o: bind
  gopkg:
    driver: local
    driver_opts:
      type: bind
      device: /var/go/pkg
      o: bind
