version: '2'
services:
  #######################################
  # DDC React Frontend
  #######################################
  app:
    image: jojomi/nginx-static
    container_name: ddc_app
    environment:
      VIRTUAL_HOST: "ddc.vm"
      VIRTUAL_PORT: "80"
    mem_limit: 100m
    volumes:
      - ./:/docker/
      - ./etc/nginx-static/default.conf:/etc/nginx/sites-enabled/default.conf
      - ../_htdocs_ddc/ddc_app/build:/var/www:ro
    networks:
      default:
        ipv4_address: 172.18.0.51

  #######################################
  # MariaDB server
  #######################################
  mariadb:
    build:
      context: docker/mariadb/
      dockerfile: MariaDB-10.2.8.Dockerfile
      # dockerfile: MariaDB-10.Dockerfile
    image: ddc_mariadb
    container_name: ddc_mariadb
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
      - ./etc/mariadb/z999-docker.cnf:/etc/mysql/conf.d/z999-docker.cnf
      - ./backup:/storage
    env_file:
      - etc/environment.yml
    mem_limit: 1g
    networks:
      default:
        ipv4_address: 172.18.0.52

  #######################################
  # KrakenD
  #######################################
  krakend:
    image: devopsfaith/krakend
    container_name: ddc_krakend
    ports:
      - "8080:8080"
      - "8090:8090"
    environment:
      VIRTUAL_HOST: "api.ddc.vm"
      VIRTUAL_PORT: "8080"
    mem_limit: 100m
    volumes:
      - ./:/docker/
      - ./etc/krakend/krakend.json:/etc/krakend/krakend.json
    networks:
      default:
        ipv4_address: 172.18.0.53
    extra_hosts:
      - "service01:172.18.0.1"

  #######################################
  # Beego
  #######################################
  beego:
    extends:
      file: common-services.yml
      service: beego
    # image: natansdj/go-beego
    container_name: ddc_beego
    links:
      - mariadb
    expose:
      - "8080"
    environment:
      VIRTUAL_HOST: "beego.vm"
      VIRTUAL_PORT: "8080"
    networks:
      default:
        ipv4_address: 172.18.0.54
    working_dir: "/go/src/github.com/natansdj/beego_docker"

#######################################
# Volumes
#######################################
volumes:
  mariadb:
    driver: local
    driver_opts:
      device: /home/lxc/mariadb/db
      o: bind
  gosrc:
    driver: local
    driver_opts:
      device: /home/ip310/go/src
      o: bind
  gopkg:
    driver: local
    driver_opts:
      device: /home/ip310/go/pkg
      o: bind

networks:
  default:
    external:
      name: dev
