###
# Docker image
# with libvips support
# natansdj/go-beego:1.17-libvips
###
ARG GO_VERSION=1.17

#Base image is in https://registry.hub.docker.com/_/golang/
#Refer to https://blog.golang.org/docker for usage
FROM golang:${GO_VERSION}

ENV GOPATH /go

# Install beego & bee
RUN go get github.com/astaxie/beego
RUN go get github.com/go-delve/delve/cmd/dlv
RUN go install github.com/beego/bee@v1.12.3
