FROM natansdj/go-beego:latest

ENV GOPATH /go

#RUN apt-get update && apt-get install -y --no-install-recommends \
#    netcat \
# && rm -rf /var/lib/apt/lists/*

RUN rm -f /etc/localtime \
    && ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
    && dpkg-reconfigure -f noninteractive tzdata
