###
# Docker image
# natansdj/go-beego
###
ARG GO_VERSION=1.18

#Base image is in https://registry.hub.docker.com/_/golang/
#Refer to https://blog.golang.org/docker for usage
FROM golang:${GO_VERSION}

ENV GOPATH /go

# Install beego & bee
RUN go install github.com/beego/bee@v1.12.3
