version: '2.1'
services:
  #######################################
  # Helper Service
  #######################################
#  cron:
#    extends:
#      file: common-services.yml
#      service: beego
#    container_name: ddc_cron
#    ports:
#      - "8199:8199"
#    mem_limit: 100m
#    networks:
#      default:
#        ipv4_address: 172.18.0.199
#    working_dir: "/go/src/ddc_cron"
#    entrypoint: "./run.sh"

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "8000:8000"
      - "9001:9000"
    mem_limit: 500m
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer_data:/data
    extra_hosts:
      - "servicestaging01:172.16.0.46"
    networks:
      default:
        ipv4_address: 172.18.0.5

  #######################################
  # DDC Services
  #######################################
  article:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_article
    ports:
      - "8091:8091"
    environment:
      GO_SVC: "ddc_article"
    networks:
      default:
        ipv4_address: 172.18.0.91
    working_dir: "/go/src/ddc_article"
    entrypoint: "./ddc_article"

  auth:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_auth
    ports:
      - "8083:8083"
    expose:
      - "2345"
    environment:
      GO_SVC: "ddc_authentication"
    networks:
      default:
        ipv4_address: 172.18.0.83
    working_dir: "/go/src/ddc_authentication"
    entrypoint: "./ddc_authentication"

  challenge:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_challenge
    ports:
      - "8092:8092"
    environment:
      GO_SVC: "ddc_challenge"
    networks:
      default:
        ipv4_address: 172.18.0.92
    working_dir: "/go/src/ddc_challenge"
    entrypoint: "./ddc_challenge"

  # cors:
  #   extends:
  #     file: common-services.yml
  #     service: beego
  #   container_name: ddc_cors
  #   ports:
  #     - "8079:8079"
  #   networks:
  #     default:
  #       ipv4_address: 172.18.0.79
  #   working_dir: "/go/src/ddc_cors"

  notification:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_notification
    ports:
      - "8082:8082"
    environment:
      GO_SVC: "ddc_notification"
    networks:
      default:
        ipv4_address: 172.18.0.82
    working_dir: "/go/src/ddc_notification"
    entrypoint: "./ddc_notification"

  product:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_product
    ports:
      - "8084:8084"
    environment:
      GO_SVC: "ddc_product"
    networks:
      default:
        ipv4_address: 172.18.0.84
    working_dir: "/go/src/ddc_product"
    entrypoint: "./ddc_product"

  payment:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_payment
    ports:
      - "8087:8087"
    environment:
      GO_SVC: "ddc_payment"
    networks:
      default:
        ipv4_address: 172.18.0.87
    working_dir: "/go/src/ddc_payment"
    entrypoint: "./ddc_payment"

  profile:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_profile
    ports:
      - "8086:8086"
    environment:
      GO_SVC: "ddc_profile"
    networks:
      default:
        ipv4_address: 172.18.0.86
    working_dir: "/go/src/ddc_profile"
    entrypoint: "./ddc_profile"

  scheduler:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_scheduler
    ports:
      - "8088:8088"
    environment:
      GO_SVC: "ddc_scheduler"
    networks:
      default:
        ipv4_address: 172.18.0.88
    working_dir: "/go/src/ddc_scheduler"
    entrypoint: "./ddc_scheduler"

  shipping:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_shipping
    ports:
      - "8081:8081"
    environment:
      GO_SVC: "ddc_shipping"
    networks:
      default:
        ipv4_address: 172.18.0.81
    working_dir: "/go/src/ddc_shipping"
    entrypoint: "./ddc_shipping"

  event:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_event
    ports:
      - "8093:8093"
    environment:
      GO_SVC: "ddc_event"
    networks:
      default:
        ipv4_address: 172.18.0.93
    working_dir: "/go/src/ddc_event"
    entrypoint: "./ddc_event"

  order:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_order
    ports:
      - "8085:8085"
    expose:
      - "18085"
    environment:
      GO_SVC: "ddc_order"
    networks:
      default:
        ipv4_address: 172.18.0.85
    working_dir: "/go/src/ddc_order"
    entrypoint: "./ddc_order"

  voucher:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_voucher
    ports:
      - "8089:8089"
    environment:
      GO_SVC: "ddc_voucher"
    networks:
      default:
        ipv4_address: 172.18.0.89
    working_dir: "/go/src/ddc_voucher"
    entrypoint: "./ddc_voucher"

  discount:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_discount
    ports:
      - "8094:8094"
    environment:
      GO_SVC: "ddc_discount"
    networks:
      default:
        ipv4_address: 172.18.0.94
    working_dir: "/go/src/ddc_discount"
    entrypoint: "./ddc_discount"

  queue:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_queue
    ports:
      - "8095:8095"
    environment:
      GO_SVC: "ddc_queue"
    networks:
      default:
        ipv4_address: 172.18.0.95
    working_dir: "/go/src/ddc_queue"
    entrypoint: "./ddc_queue"

  mentoring:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_mentoring
    ports:
      - "8096:8096"
    environment:
      GO_SVC: "ddc_mentoring"
    networks:
      default:
        ipv4_address: 172.18.0.96
    working_dir: "/go/src/ddc_mentoring"
    entrypoint: "./ddc_mentoring"

  arisan:
    extends:
      file: common-services.yml
      service: beego
    container_name: ddc_arisan
    ports:
      - "8097:8097"
    environment:
      GO_SVC: "ddc_arisan"
    networks:
      default:
        ipv4_address: 172.18.0.97
    working_dir: "/go/src/ddc_arisan"

#######################################
# Volumes
#######################################
volumes:
  gosrc:
    driver: local
    driver_opts:
      type: bind
      device: /var/www/go/src
      o: bind
  gopkg:
    driver: local
    driver_opts:
      type: bind
      device: /var/www/go/pkg
      o: bind

networks:
  default:
    external:
      name: dev
