version: '2'
services:
  #######################################
  # DDC React Frontend
  #######################################
  app:
    image: jojomi/nginx-static
    container_name: ddc_app
    networks:
      - default
    environment:
      VIRTUAL_HOST: "ddc.vm"
      VIRTUAL_PORT: "80"
    mem_limit: 100m
    volumes:
      - ./:/docker/
      - ./etc/nginx-static/default.conf:/etc/nginx/sites-enabled/default.conf
      - ../_htdocs_ddc/ddc_app/build:/var/www:ro
    networks:
      default:
        ipv4_address: 172.18.0.51

  #######################################
  # MariaDB server
  #######################################
  mariadb:
    build:
      context: docker/mariadb/
      dockerfile: MariaDB-10.Dockerfile
    image: ddc_mariadb
    container_name: ddc_mariadb
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
      - ./backup:/storage
    env_file:
      - etc/environment.yml
      - etc/environment.development.yml
    mem_limit: 1g
    networks:
      default:
        ipv4_address: 172.18.0.52

  #######################################
  # KrakenD
  #######################################
  krakend:
    image: devopsfaith/krakend
    container_name: ddc_krakend
    networks:
      - default
    ports:
      - "8080:8080"
      - "8090:8090"
    environment:
      VIRTUAL_HOST: "api.ddc.vm"
      VIRTUAL_PORT: "8080"
      # HOST_HOSTNAME: "service01"
    mem_limit: 100m
    volumes:
      - ./:/docker/
      - ./etc/krakend/krakend.json:/etc/krakend/krakend.json
    networks:
      default:
        ipv4_address: 172.18.0.53

  #######################################
  # Beego
  #######################################
  beego:
    build:
      context: .
    image: ddc_beego
    container_name: ddc_beego
    networks:
      - default
    links:
      - mariadb
    ports:
      - "28080:8080"
    # cap and privileged needed for slowlog
    cap_add:
      - SYS_PTRACE
    privileged: true
    environment:
      VIRTUAL_HOST: "beego.vm"
      VIRTUAL_PORT: "8080"
    mem_limit: 200m
    volumes:
      - ./:/docker/
      - gosrc:/go/src/
      - gopkg:/go/pkg/
    networks:
      default:
        ipv4_address: 172.18.0.54
    working_dir: "/go/src/github.com/natansdj/beego_docker"
    entrypoint: "bee run"

  #######################################
  # DDC Services
  #######################################
  cors:
    image: natansdj/go-beego
    container_name: ddc_cors
    links:
      - mariadb
    ports:
      - "8079:8079"
    environment:
      VIRTUAL_HOST: "cors.ddc.vm"
      VIRTUAL_PORT: "8079"
    mem_limit: 200m
    volumes:
      - ./:/docker/
      - gosrc:/go/src/
      - gopkg:/go/pkg/
    working_dir: "/go/src/ddc_cors"
    entrypoint: "bee run"
  authentication:
    image: natansdj/go-beego
    container_name: ddc_authentication
    links:
      - mariadb
    ports:
      - "8083:8083"
    environment:
      VIRTUAL_HOST: "auth.ddc.vm"
      VIRTUAL_PORT: "8083"
    mem_limit: 200m
    volumes:
      - ./:/docker/
      - gosrc:/go/src/
      - gopkg:/go/pkg/
    working_dir: "/go/src/ddc_authentication"
    entrypoint: "bee run"
  profile:
    image: natansdj/go-beego
    container_name: ddc_profile
    links:
      - mariadb
    ports:
      - "8086:8086"
    environment:
      VIRTUAL_HOST: "profile.ddc.vm"
      VIRTUAL_PORT: "8086"
    mem_limit: 200m
    volumes:
      - ./:/docker/
      - gosrc:/go/src/
      - gopkg:/go/pkg/
    working_dir: "/go/src/ddc_profile"
    entrypoint: "bee run"

#######################################
# Volumes
#######################################
volumes:
  mariadb:
    driver: local
    driver_opts:
      device: /home/lxc/mariadb/db
      o: bind
  gosrc:
    driver: local
    driver_opts:
      device: /home/ip310/go/src
      o: bind
  gopkg:
    driver: local
    driver_opts:
      device: /home/ip310/go/pkg
      o: bind

networks:
  default:
    external:
      name: dev
