###
# Docker image
# natansdj/go-beego:1.18-libvips | with libvips support
###
FROM natansdj/go-beego:1.18

RUN apt-get update && apt-get install -y \
  pkg-config \
  libvips-dev \
  libvips \
  libvips-tools \
  libvips42 \
 && apt-get clean \
 && rm -rf /var/cache/apt/archives /var/lib/apt/lists/*
