###
# Docker image
# natansdj/go-beego:1.18
###
ARG GO_VERSION=1.18

#Base image is in https://registry.hub.docker.com/_/golang/
#Refer to https://blog.golang.org/docker for usage
FROM golang:${GO_VERSION}

ENV GOPATH /go
ENV GOBIN $GOPATH/bin

# Install beego & bee
RUN go install github.com/beego/bee@v1.12.3 \
  && bee version
